version: "3.9"
services:
  api:
    image: python:3.12-slim
    working_dir: /app
    command: sh -c "pip install -r requirements.txt && uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload"
    volumes:
      - ./src:/app
      - ./data/uploads:/data/uploads
      - ./requirements.txt:/app/requirements.txt
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - REDIS_URL=${REDIS_URL}
      - UPLOAD_DIR=${UPLOAD_DIR}
      - DEFAULT_MSG_RATE_RPS=${DEFAULT_MSG_RATE_RPS}
      - DEFAULT_UPLOAD_BPS=${DEFAULT_UPLOAD_BPS}
      - DEFAULT_DOWNLOAD_BPS=${DEFAULT_DOWNLOAD_BPS}
      - DEFAULT_BURST=${DEFAULT_BURST}
      - DEV_MODE=${DEV_MODE}
      - SECRET_KEY=${SECRET_KEY}
    depends_on:
      - db
      - redis
    ports:
      - "8000:8000"

  db:
    image: postgres:16
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=chat
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"

volumes:
  pgdata:
  src:
